services:
  go2rtc:
    # command: tail -f /dev/null
    image: alexxit/go2rtc
    container_name: go2rtc
      #network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: unless-stopped  # autorestart on fail or config change from WebUI
    environment:
      - TZ=America/Chicago  # timezone in logs
    volumes:
      - go2rtc:/config   # folder for go2rtc.yaml file (edit from WebUI)
    ports:
      - 127.0.0.1:1984:1984
      - 127.0.0.1:8554:8554 
      - 127.0.0.1:8443:8443
      - 127.0.0.1:8555:8555
volumes:
  go2rtc:
